using System.Windows.Media;
using Smurftown.Backend.Entity;

namespace Smurftown.UI.MVVM;

/// <summary>
///     The one place that maps a hero to its portrait. Picker, dialog preview,
///     filter bar and card all access it - the derivation must not drift apart at
///     multiple places the way the battletag-to-Windows-user derivation did.
///     <para>
///         JPEG instead of PNG like the rest of the image folder: the portraits are photographs without
///         transparency, and the circle is only created in WPF (Ellipse + ImageBrush), not in the
///         asset. Generated by <c>tools/build-hero-assets.py</c>.
///     </para>
/// </summary>
static class HotsHeroImages
{
    private const string Folder = "pack://application:,,,/UI/Images/Heroes/";

    public static string PathFor(HotsHero hero)
    {
        return Folder + hero.Id + ".jpg";
    }
}

/// <summary>
///     Color per hero role. In-game heroes carry no role color - the coding is our own
///     addition, so that 90 circles get an order. It therefore sits in the ring around the portrait
///     and not in the image: the portrait stays untouched, the ring disappears with the selection.
///     <para>Six shades of similar brightness, legible on the app's dark background.</para>
/// </summary>
static class HotsRoleColors
{
    /// <summary>Ring of a hero not owned - neutral, so that only the selection carries color.</summary>
    public static readonly SolidColorBrush Unselected = Frozen("#3A3D46");

    private static readonly Dictionary<HotsHeroRole, SolidColorBrush> ByRole = new()
    {
        [HotsHeroRole.Tank] = Frozen("#4C86C6"),
        [HotsHeroRole.Bruiser] = Frozen("#B5703C"),
        [HotsHeroRole.MeleeAssassin] = Frozen("#C4453F"),
        [HotsHeroRole.RangedAssassin] = Frozen("#A45FC0"),
        [HotsHeroRole.Healer] = Frozen("#4FA36B"),
        [HotsHeroRole.Support] = Frozen("#C9A63A")
    };

    public static SolidColorBrush For(HotsHeroRole role)
    {
        return ByRole.TryGetValue(role, out var brush) ? brush : Unselected;
    }

    private static SolidColorBrush Frozen(string hex)
    {
        var brush = new SolidColorBrush((Color)ColorConverter.ConvertFromString(hex)!);
        brush.Freeze();
        return brush;
    }
}
