namespace Smurftown.Backend.Entity
{
    /// <summary>
    ///     Lookups against the hero table. The table itself lives in
    ///     <c>HotsHeroCatalog.Generated.cs</c> and is generated by <c>tools/build-hero-assets.py</c>
    ///     together with the portraits - id and file name therefore come from a single
    ///     run and cannot drift apart.
    /// </summary>
    public static partial class HotsHeroCatalog
    {
        // Lazy and not as a field initializer: the indexes live in this file, the
        // table All in the generated one. Across file boundaries the order of
        // static initializers is not guaranteed - built as a field, All might
        // still be null here.
        private static Dictionary<string, HotsHero>? _byId;
        private static Dictionary<HotsHeroRole, IReadOnlyList<HotsHero>>? _byRole;

        private static Dictionary<string, HotsHero> ById =>
            _byId ??= All.ToDictionary(h => h.Id, StringComparer.OrdinalIgnoreCase);

        private static Dictionary<HotsHeroRole, IReadOnlyList<HotsHero>> ByRoleIndex =>
            _byRole ??= All.GroupBy(h => h.Role)
                .ToDictionary(g => g.Key, g => (IReadOnlyList<HotsHero>)g.ToList());

        /// <summary>Count of all heroes - the reference size for every "x / 90" display.</summary>
        public static int Count => All.Count;

        /// <summary>
        ///     Hero for an id, or <c>null</c>. Null is not an error case: a <c>data.yaml</c>
        ///     written by a newer app version can contain ids this version doesn't know.
        ///     Those are skipped, not reported.
        /// </summary>
        public static HotsHero? Find(string? id)
        {
            return id != null && ById.TryGetValue(id, out var hero) ? hero : null;
        }

        /// <summary>All heroes of a role, in display order.</summary>
        public static IReadOnlyList<HotsHero> ByRole(HotsHeroRole role)
        {
            return ByRoleIndex.TryGetValue(role, out var heroes) ? heroes : [];
        }

        /// <summary>
        ///     Resolves ids to heroes. The result is in display order and without
        ///     duplicates, regardless of how the list was sorted in <c>data.yaml</c>.
        ///     Unknown ids are dropped.
        /// </summary>
        public static IReadOnlyList<HotsHero> Resolve(IEnumerable<string>? ids)
        {
            if (ids == null) return [];
            var wanted = new HashSet<string>(ids, StringComparer.OrdinalIgnoreCase);
            return wanted.Count == 0 ? [] : All.Where(h => wanted.Contains(h.Id)).ToList();
        }
    }
}
