namespace Battledeck.Backend.Entity
{
    /// <summary>
    ///     A hero from Heroes of the Storm.
    ///     <para>
    ///         <see cref="Id" /> is at the same time the file name of the portrait
    ///         (<c>UI/Images/Heroes/{Id}.jpg</c>) and the value in <c>data.yaml</c>. That's why
    ///         it carries no accents, apostrophes or periods: "lucio", "anubarak",
    ///         "lt-morales". One key for both instead of two that could drift apart.
    ///     </para>
    ///     The table of all heroes is generated by <c>tools/build-hero-assets.py</c>.
    /// </summary>
    /// <param name="Name">The English display name - what appears in the app.</param>
    /// <param name="GermanName">
    ///     The name the German game client displays. It is only needed when reading: the
    ///     collection writes it under every card, and OCR returns exactly this text back. It
    ///     stands here and not in a second table, so it comes from the same run together with
    ///     the id - the same reasoning as with the portrait.
    ///     <para>
    ///         Mostly the same as the English name; differs in about a dozen cases, e.g.
    ///         Funkelchen (Brightwing), Todesschwinge (Deathwing), Der Schlaechter (The Butcher),
    ///         Kleiner (Stitches).
    ///     </para>
    /// </param>
    public sealed record HotsHero(string Id, string Name, string GermanName, HotsHeroRole Role);
}
